# Generated by Django 4.2 on 2024-03-24 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_category_options_alter_tag_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                max_length=200,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator("^[a-zA-Z0-9_-]+$")
                ],
                verbose_name="Слаг",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="weight",
            field=models.IntegerField(
                blank=True,
                default=100,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(32767),
                ],
                verbose_name="Вес",
            ),
        ),
    ]
